name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
        check-latest: true  
    
    - name: enable web
      run: flutter config --enable-web

    - name: Get dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test  

    - name: Build Web App
      run: flutter build web

    - name: Build Android App
#      run: flutter build apk --verbose
      run: flutter build apk

    - name: Create Container for web
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flutterfr0g:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flutterfr0g:latest

    - name: rename apk
      run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/fr0gsite.apk